name: Crawl Companies

on:
  workflow_dispatch:  # cho phép chạy thủ công

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3️⃣ Cài đặt Chrome, Tesseract và các thư viện Python
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium tesseract-ocr

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt
      # 4️⃣ Chạy crawler
      - name: Run crawler script
        run: |
          python crawl_script.py

      # 5️⃣ Upload data ra artifact (dùng version mới)
      - name: Upload crawled data
        uses: actions/upload-artifact@v4
        with:
          name: company-data
          path: data/ho-chi-minh/
