name: Crawl Companies

on:
  schedule:
    - cron: "0 */6 * * *"   # chạy mỗi 6 tiếng
  workflow_dispatch:        # có thể bấm nút chạy tay

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr unzip
          # Cài Google Chrome
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          # Lấy ChromeDriver cùng version
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION%.*}")
          wget "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          rm chromedriver_linux64.zip
          python -m pip install --upgrade pip

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run crawler
        env:
      
        run: |
          python main.py
          python demo.py

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: excel-files
          path: data/ho-chi-minh/
